import type { SystemUser } from "@/types/system";
import type { Tone } from "@/types/common";

const s = (label: string, tone: Tone) => ({ label, tone });

/** Reshaped from SYSTEM_CONFIGS.users' four tabs (workspace/data/system.ts:114-137) into one
 * canonical roster. Where the same person appeared with a stricter status under "Access review"
 * (e.g. Arjun P.'s 2FA, Latha S./Kiran D.'s review-due) that stricter status wins as the single
 * source of truth, and `flagged` reproduces the "Access review" tab as a filter. */
export const SEED_SYSTEM_USERS: SystemUser[] = [
  {
    id: "usr-arun-k",
    name: "Arun K.",
    role: "Super Admin",
    scope: "All",
    email: "arun@selorg.in",
    moduleCount: "26",
    sensitiveRights: "Approve, Refund, Export",
    lastLogin: "Today 18:40",
    twoFactor: "On",
    status: s("Active", "green"),
    accountStatus: "active",
    flagged: false,
  },
  {
    id: "usr-nisha-r",
    name: "Nisha R.",
    role: "Dark Store Manager",
    scope: "DS-01",
    email: "nisha@selorg.in",
    moduleCount: "9",
    sensitiveRights: "Assign",
    lastLogin: "Today 18:12",
    twoFactor: "On",
    status: s("Active", "green"),
    accountStatus: "active",
    flagged: false,
  },
  {
    id: "usr-mahesh-b",
    name: "Mahesh B.",
    role: "Warehouse Manager",
    scope: "WH-01",
    email: "mahesh@selorg.in",
    moduleCount: "8",
    sensitiveRights: "Approve",
    lastLogin: "Today 17:55",
    twoFactor: "On",
    status: s("Active", "green"),
    accountStatus: "active",
    flagged: false,
  },
  {
    id: "usr-latha-s",
    name: "Latha S.",
    role: "Finance Admin",
    scope: "All",
    email: "latha@selorg.in",
    moduleCount: "6",
    sensitiveRights: "Refund, Export",
    lastLogin: "Today 18:31",
    twoFactor: "On",
    status: s("Due review", "amber"),
    accountStatus: "active",
    flagged: true,
  },
  {
    id: "usr-arjun-p",
    name: "Arjun P.",
    role: "Rider Manager",
    scope: "All hubs",
    email: "arjun@selorg.in",
    moduleCount: "5",
    sensitiveRights: "Assign",
    lastLogin: "Today 19:01",
    twoFactor: "Off",
    status: s("2FA missing", "red"),
    accountStatus: "active",
    flagged: true,
  },
  {
    id: "usr-kiran-d",
    name: "Kiran D.",
    role: "Operations Admin",
    scope: "All",
    email: "kiran@selorg.in",
    moduleCount: "14",
    sensitiveRights: "Approve, Assign",
    lastLogin: "Yesterday",
    twoFactor: "On",
    status: s("Due review", "amber"),
    accountStatus: "active",
    flagged: true,
  },
  {
    id: "usr-pooja-v",
    name: "Pooja V.",
    role: "Customer Support",
    scope: "Global",
    email: "pooja@selorg.in",
    moduleCount: "6",
    sensitiveRights: "Refund (≤ ₹500)",
    lastLogin: "—",
    twoFactor: "Pending",
    status: s("Invited", "amber"),
    accountStatus: "invited",
    flagged: false,
  },
  {
    id: "usr-ravi-t",
    name: "Ravi T.",
    role: "Dark Store Manager",
    scope: "DS-06",
    email: "ravi@selorg.in",
    moduleCount: "9",
    sensitiveRights: "Assign",
    lastLogin: "—",
    twoFactor: "Pending",
    status: s("Invited", "amber"),
    accountStatus: "invited",
    flagged: false,
  },
  {
    id: "usr-sunil-m",
    name: "Sunil M.",
    role: "Warehouse Manager",
    scope: "WH-02",
    email: "sunil@selorg.in",
    moduleCount: "8",
    sensitiveRights: "Approve",
    lastLogin: "—",
    twoFactor: "Pending",
    status: s("Expiring", "red"),
    accountStatus: "invited",
    flagged: false,
  },
  {
    id: "usr-vinay-s",
    name: "Vinay S.",
    role: "Dark Store Manager",
    scope: "DS-02",
    email: "vinay@selorg.in",
    moduleCount: "0",
    sensitiveRights: "—",
    lastLogin: "14 Aug",
    twoFactor: "—",
    status: s("Deactivated", "grey"),
    accountStatus: "deactivated",
    flagged: false,
  },
  {
    id: "usr-neha-b",
    name: "Neha B.",
    role: "Customer Support",
    scope: "Global",
    email: "neha@selorg.in",
    moduleCount: "0",
    sensitiveRights: "—",
    lastLogin: "02 Aug",
    twoFactor: "—",
    status: s("Deactivated", "grey"),
    accountStatus: "deactivated",
    flagged: false,
  },
];
