// GENERATED by scripts/generate-ops-screens.mjs from design-reference/Selorg Admin Dashboard.dc.html.
// Action dialogs (fields, whether the action advances the record's flow). Do not edit by hand — re-run the generator.
import type { OpsActionForm } from "@/modules/ops/types";

export const GENERATED_ACTION_FORMS: Record<string, OpsActionForm> = {
  "Add stop": {
    "advances": true,
    "fields": [
      {
        "id": "order2",
        "label": "Order",
        "kind": "select",
        "options": [
          "SEL-104815 Karthik S.",
          "SEL-104803 Sneha Gupta",
          "SEL-104827 Girish P."
        ],
        "required": true
      },
      {
        "id": "pos",
        "label": "Insert at",
        "kind": "select",
        "options": [
          "Optimal position",
          "End of route",
          "Specific position"
        ],
        "required": true
      },
      {
        "id": "impact",
        "label": "Impact",
        "kind": "select",
        "options": [
          "Within capacity and windows",
          "Adds 1.2 km — accept",
          "Breaks a window — reject"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Add to existing batch": {
    "advances": true,
    "fields": [
      {
        "id": "batch",
        "label": "Batch",
        "kind": "select",
        "options": [
          "BDB-2045 Indiranagar · 6 stops",
          "BDB-2046 HSR Layout · 5 stops",
          "BDB-2047 Koramangala · 6 stops"
        ],
        "required": true
      },
      {
        "id": "check",
        "label": "Impact",
        "kind": "select",
        "options": [
          "Capacity and window both fit",
          "Adds distance — accept",
          "Needs re-optimisation"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Adjust incentive": {
    "advances": true,
    "fields": [
      {
        "id": "dir",
        "label": "Adjustment",
        "kind": "select",
        "options": [
          "Add",
          "Deduct"
        ],
        "required": true
      },
      {
        "id": "amount",
        "label": "Amount (₹)",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Rule missed a conversion",
          "Invalid conversion reversed",
          "Goodwill",
          "Data correction",
          "Manager discretion"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Justification",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Allocate samples": {
    "advances": true,
    "fields": [
      {
        "id": "product",
        "label": "Product",
        "kind": "select",
        "options": [
          "Organic Tomato 100g pack",
          "Amul Gold Milk 200ml",
          "Paneer 50g cube",
          "Yoghurt 80g cup",
          "Cold Pressed Oil 50ml",
          "Farm Eggs 2pc",
          "Basmati Rice 100g"
        ],
        "required": true
      },
      {
        "id": "qty",
        "label": "Quantity",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "from",
        "label": "Distribute from",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "to",
        "label": "Until",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Apply route": {
    "advances": true,
    "fields": [
      {
        "id": "confirm",
        "label": "Apply",
        "kind": "select",
        "options": [
          "Optimised sequence",
          "Manual sequence"
        ],
        "required": true
      },
      {
        "id": "lockit",
        "label": "Lock for dispatch",
        "kind": "select",
        "options": [
          "Yes",
          "No — allow further edits"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Approve allocation": {
    "advances": true,
    "fields": [
      {
        "id": "qty",
        "label": "Approved quantity",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "from",
        "label": "Source",
        "kind": "select",
        "options": [
          "Marketing stock",
          "Warehouse — marketing account",
          "Vendor sample supply"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Approve earning": {
    "advances": true,
    "fields": [
      {
        "id": "period",
        "label": "Period",
        "kind": "select",
        "options": [
          "This week",
          "Last week",
          "Custom"
        ],
        "required": true
      },
      {
        "id": "check",
        "label": "Confirmed",
        "kind": "select",
        "options": [
          "Rules applied correctly",
          "Manual review completed"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Approve rule": {
    "advances": true,
    "fields": [
      {
        "id": "scope",
        "label": "Approving",
        "kind": "select",
        "options": [
          "This version only",
          "Version and schedule"
        ],
        "required": true
      },
      {
        "id": "effective",
        "label": "Effective from",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Assign advertisement": {
    "advances": true,
    "fields": [
      {
        "id": "ad",
        "label": "Advertisement",
        "kind": "select",
        "options": [
          "Monsoon Fresh Launch",
          "First Order Free Delivery",
          "Dairy Under ₹99",
          "Onam Special",
          "Weekend Sampling Drive"
        ],
        "required": true
      },
      {
        "id": "from",
        "label": "Live from",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "to",
        "label": "Until",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Assign batch": {
    "advances": true,
    "fields": [
      {
        "id": "batch2",
        "label": "Batch",
        "kind": "select",
        "options": [
          "BDB-2046 HSR Layout · 5 stops",
          "BDB-2047 Koramangala · 6 stops"
        ],
        "required": true
      },
      {
        "id": "vehicle3",
        "label": "Vehicle",
        "kind": "select",
        "options": [
          "KA-51 CD 1120 · Jeeto",
          "KA-03 KL 6620 · Tata Ace"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Assign driver": {
    "advances": true,
    "fields": [
      {
        "id": "driver",
        "label": "Rider / operator",
        "kind": "select",
        "options": [
          "Kiran D.",
          "Anil V.",
          "Suresh N.",
          "Ramesh Y.",
          "Vinod P.",
          "Vikram J.",
          "Imran A.",
          "Naveen R.",
          "Deepak T."
        ],
        "required": true
      },
      {
        "id": "mode",
        "label": "Delivery mode",
        "kind": "select",
        "options": [
          "Single · cycle (1–2 orders)",
          "Single · bike (up to 3 orders)",
          "Bulk · e-auto (40–50 orders)"
        ],
        "required": true
      },
      {
        "id": "licence",
        "label": "Licence verified",
        "kind": "select",
        "options": [
          "Not required — cycle",
          "MCWG — two-wheeler",
          "LMV — e-auto",
          "LMV-TR — light transport"
        ],
        "required": true
      },
      {
        "id": "slot",
        "label": "Reporting time",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Assign employee": {
    "advances": true,
    "fields": [
      {
        "id": "who",
        "label": "Employee",
        "kind": "select",
        "options": [
          "EMP-121 Vinod Kumar",
          "EMP-124 Sneha D.",
          "New hire — create record"
        ],
        "required": true
      },
      {
        "id": "from",
        "label": "Effective from",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "shift",
        "label": "Stall hours",
        "kind": "select",
        "options": [
          "09:00–18:00",
          "10:00–19:00",
          "11:00–20:00"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Assign operator": {
    "advances": true,
    "fields": [
      {
        "id": "operator",
        "label": "Operator",
        "kind": "select",
        "options": [
          "Anil V.",
          "Kiran D.",
          "Suresh N.",
          "Vinod P.",
          "Ramesh Y.",
          "Imtiaz A.",
          "Prakash V."
        ],
        "required": true
      },
      {
        "id": "licence",
        "label": "Licence class",
        "kind": "select",
        "options": [
          "LMV — auto",
          "LMV-TR — light transport"
        ],
        "required": true
      },
      {
        "id": "report",
        "label": "Reporting time",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Assign rider": {
    "advances": true,
    "fields": [
      {
        "id": "rider",
        "label": "Rider",
        "kind": "select",
        "options": [
          "Vikram J.",
          "Imran A.",
          "Naveen R.",
          "Sameer Q.",
          "Deepak T."
        ],
        "required": true
      },
      {
        "id": "mode",
        "label": "Assignment",
        "kind": "select",
        "options": [
          "Manual pick",
          "Auto-suggest nearest",
          "Broadcast to zone"
        ],
        "required": true
      },
      {
        "id": "eta",
        "label": "Promise (min)",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Assign to stall": {
    "advances": true,
    "fields": [
      {
        "id": "area",
        "label": "Area",
        "kind": "select",
        "options": [
          "AREA-01 Indiranagar",
          "AREA-02 Koramangala",
          "AREA-03 HSR Layout",
          "AREA-04 Whitefield"
        ],
        "required": true
      },
      {
        "id": "stall",
        "label": "Stall",
        "kind": "select",
        "options": [
          "CS-014 Koramangala 8th",
          "CS-033 Whitefield Hope Farm",
          "CS-035 Whitefield Kadugodi"
        ],
        "required": true
      },
      {
        "id": "from",
        "label": "Effective from",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Assign to stalls": {
    "advances": true,
    "fields": [
      {
        "id": "scope",
        "label": "Assign to",
        "kind": "select",
        "options": [
          "All active stalls",
          "One area",
          "Selected stalls"
        ],
        "required": true
      },
      {
        "id": "area",
        "label": "Area",
        "kind": "select",
        "options": [
          "AREA-01 Indiranagar",
          "AREA-02 Koramangala",
          "AREA-03 HSR Layout",
          "AREA-04 Whitefield"
        ],
        "required": false
      },
      {
        "id": "from",
        "label": "Live from",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Assign to store": {
    "advances": true,
    "fields": [
      {
        "id": "store",
        "label": "Dark store",
        "kind": "select",
        "options": [
          "DS-01 Indiranagar",
          "DS-02 Koramangala",
          "DS-03 HSR Layout",
          "DS-04 Whitefield",
          "DS-05 Jayanagar"
        ],
        "required": true
      },
      {
        "id": "shift",
        "label": "Shift",
        "kind": "select",
        "options": [
          "Shift 1 (06–14)",
          "Shift 2 (14–22)",
          "Shift 3 (22–06)"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Assign vehicle": {
    "advances": true,
    "fields": [
      {
        "id": "vehicle",
        "label": "Vehicle",
        "kind": "select",
        "options": [
          "KA-05 AB 8890 · Auto · 350 kg",
          "KA-03 IJ 5580 · Auto · 350 kg",
          "KA-01 MH 4412 · Tata Ace · 750 kg",
          "KA-51 CD 1120 · Jeeto · 500 kg",
          "KA-09 GH 2240 · Auto · 350 kg"
        ],
        "required": true
      },
      {
        "id": "load",
        "label": "Estimated load (kg)",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "check",
        "label": "Capacity",
        "kind": "select",
        "options": [
          "Within capacity",
          "Near limit — accept",
          "Exceeds — split required"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Call customer": {
    "advances": false,
    "fields": [
      {
        "id": "purpose",
        "label": "Purpose",
        "kind": "select",
        "options": [
          "Confirm address",
          "Rider cannot reach",
          "Running late",
          "Delivery attempt",
          "Reschedule"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Call operator": {
    "advances": false,
    "fields": [
      {
        "id": "purpose",
        "label": "Purpose",
        "kind": "select",
        "options": [
          "Position check",
          "Delay reason",
          "Customer cannot be reached",
          "Route guidance",
          "Breakdown",
          "Skip decision"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Cancel batch": {
    "advances": false,
    "fields": [
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Too few orders",
          "No vehicle available",
          "No operator available",
          "Area suspended",
          "Orders reassigned to riders"
        ],
        "required": true
      },
      {
        "id": "orders2",
        "label": "The orders",
        "kind": "select",
        "options": [
          "Return to bulk queue",
          "Reassign to standard riders",
          "Hold at store"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Change status": {
    "advances": true,
    "fields": [
      {
        "id": "status",
        "label": "New status",
        "kind": "select",
        "options": [
          "Planned",
          "Setup pending",
          "Active",
          "Temporarily closed",
          "Maintenance",
          "Inactive"
        ],
        "required": true
      },
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Site ready",
          "Permit received",
          "Permit issue",
          "Structure repair",
          "Low footfall",
          "Relocating",
          "Seasonal"
        ],
        "required": true
      },
      {
        "id": "until",
        "label": "Reopen on",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Close temporarily": {
    "advances": false,
    "fields": [
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Permit issue",
          "Weather",
          "Local event",
          "Employee on leave",
          "Low footfall",
          "Relocating"
        ],
        "required": true
      },
      {
        "id": "until",
        "label": "Reopen on",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Close trip": {
    "advances": true,
    "fields": [
      {
        "id": "delivered",
        "label": "Stops delivered",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "failed",
        "label": "Stops failed",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "odo",
        "label": "Actual distance (km)",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "check2",
        "label": "Vehicle returned",
        "kind": "select",
        "options": [
          "Yes, at the store",
          "Parked at hub",
          "Still out"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Compare routes": {
    "advances": false,
    "fields": [
      {
        "id": "against",
        "label": "Compare optimised against",
        "kind": "select",
        "options": [
          "Current applied route",
          "Manual sequence",
          "Previous version"
        ],
        "required": true
      }
    ]
  },
  "Create new version": {
    "advances": true,
    "fields": [
      {
        "id": "change",
        "label": "What changes",
        "kind": "select",
        "options": [
          "Amount",
          "Condition",
          "Scope",
          "Effective dates"
        ],
        "required": true
      },
      {
        "id": "value",
        "label": "New value",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "from",
        "label": "Effective from",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "note",
        "label": "Reason for change",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Deactivate stall": {
    "advances": false,
    "fields": [
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Site lost",
          "Persistently low conversion",
          "Area restructure",
          "Permit revoked",
          "Replaced by new stall"
        ],
        "required": true
      },
      {
        "id": "staff",
        "label": "Assigned employee",
        "kind": "select",
        "options": [
          "Reassign to another stall",
          "Move to unassigned pool",
          "Exiting the company"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Dispatch batch": {
    "advances": true,
    "fields": [
      {
        "id": "time",
        "label": "Departure time",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "eta",
        "label": "Last stop ETA",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "notify",
        "label": "Notify customers",
        "kind": "select",
        "options": [
          "Yes, all stops with ETA",
          "Yes, first stop only",
          "No"
        ],
        "required": true
      },
      {
        "id": "docs",
        "label": "With the operator",
        "kind": "select",
        "options": [
          "Delivery list + invoices",
          "Delivery list only"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Dispatch load": {
    "advances": true,
    "fields": [
      {
        "id": "time",
        "label": "Departure time",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "eta",
        "label": "ETA at site",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "notify",
        "label": "Notify customer",
        "kind": "select",
        "options": [
          "Yes, with tracking link",
          "Yes, SMS only",
          "No"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Edit stall": {
    "advances": true,
    "fields": [
      {
        "id": "name",
        "label": "Stall name",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "address",
        "label": "Address",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "hours",
        "label": "Operating hours",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "days",
        "label": "Operating days",
        "kind": "select",
        "options": [
          "All days",
          "Mon–Sat",
          "Weekends only"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Reason for change",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "End campaign": {
    "advances": false,
    "fields": [
      {
        "id": "when",
        "label": "End",
        "kind": "select",
        "options": [
          "Immediately",
          "End of day",
          "End of week"
        ],
        "required": true
      },
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Budget met",
          "Target achieved",
          "Low ROI",
          "Replaced"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Escalate": {
    "advances": false,
    "fields": [
      {
        "id": "to",
        "label": "Escalate to",
        "kind": "select",
        "options": [
          "Ops lead",
          "Warehouse manager",
          "Finance admin",
          "Super Admin"
        ],
        "required": true
      },
      {
        "id": "severity",
        "label": "Severity",
        "kind": "select",
        "options": [
          "High",
          "Critical"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Reason",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Exclude from bulk": {
    "advances": false,
    "fields": [
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Address invalid",
          "Outside area",
          "Fragile — single delivery",
          "Customer requested rider",
          "Too far from cluster"
        ],
        "required": true
      },
      {
        "id": "route2",
        "label": "Deliver instead by",
        "kind": "select",
        "options": [
          "Standard rider",
          "Next batch",
          "Hold at store"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Expire rule": {
    "advances": false,
    "fields": [
      {
        "id": "when",
        "label": "Expire",
        "kind": "select",
        "options": [
          "Immediately",
          "End of today",
          "End of cycle"
        ],
        "required": true
      },
      {
        "id": "replace",
        "label": "Replaced by",
        "kind": "select",
        "options": [
          "Nothing",
          "New version",
          "Different rule"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Export view": {
    "advances": false,
    "fields": [
      {
        "id": "scope",
        "label": "Rows",
        "kind": "select",
        "options": [
          "Everything in this tab",
          "Only what is filtered",
          "Selected columns only"
        ],
        "required": true
      },
      {
        "id": "format",
        "label": "Format",
        "kind": "select",
        "options": [
          "CSV",
          "Excel",
          "PDF",
          "JSON"
        ],
        "required": true
      },
      {
        "id": "delivery",
        "label": "Deliver",
        "kind": "select",
        "options": [
          "Download now",
          "Email to me",
          "Save to reports"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Extend window": {
    "advances": true,
    "fields": [
      {
        "id": "until",
        "label": "Extend until",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "budget",
        "label": "Additional budget (₹)",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Flag as invalid": {
    "advances": false,
    "fields": [
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Customer already existed",
          "Self-registered by employee",
          "Duplicate device",
          "Order cancelled immediately",
          "Suspected fraud"
        ],
        "required": true
      },
      {
        "id": "incentive",
        "label": "Incentive",
        "kind": "select",
        "options": [
          "Reverse the incentive",
          "Leave incentive in place"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Evidence",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Group into batch": {
    "advances": true,
    "fields": [
      {
        "id": "area",
        "label": "Area",
        "kind": "select",
        "options": [
          "AREA-01 Indiranagar",
          "AREA-02 Koramangala",
          "AREA-03 HSR Layout",
          "AREA-04 Whitefield"
        ],
        "required": true
      },
      {
        "id": "orders",
        "label": "Orders to include",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "window",
        "label": "Delivery window",
        "kind": "select",
        "options": [
          "Next 45 minutes",
          "Next hour",
          "All ready orders"
        ],
        "required": true
      },
      {
        "id": "vtype",
        "label": "Vehicle class needed",
        "kind": "select",
        "options": [
          "Auto rickshaw · up to 350 kg",
          "Pickup · up to 500 kg",
          "Mini truck · up to 750 kg",
          "Decide after capacity check"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Hold payment": {
    "advances": false,
    "fields": [
      {
        "id": "scope",
        "label": "Hold",
        "kind": "select",
        "options": [
          "Incentive only",
          "Salary and incentive"
        ],
        "required": true
      },
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Conversions under review",
          "Employee suspended",
          "Bank details invalid",
          "Investigation open"
        ],
        "required": true
      },
      {
        "id": "until",
        "label": "Review on",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Lock stop": {
    "advances": true,
    "fields": [
      {
        "id": "stop",
        "label": "Stop",
        "kind": "select",
        "options": [
          "Stop 1",
          "Stop 2",
          "Stop 3",
          "Stop 4",
          "Stop 5",
          "Stop 6"
        ],
        "required": true
      },
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Customer requested time",
          "Perishable order",
          "Corporate account",
          "Compensation"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Log maintenance": {
    "advances": true,
    "fields": [
      {
        "id": "type",
        "label": "Work",
        "kind": "select",
        "options": [
          "Scheduled service",
          "Repair",
          "Tyres",
          "Battery",
          "Bodywork"
        ],
        "required": true
      },
      {
        "id": "from",
        "label": "Off road from",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "days",
        "label": "Expected days",
        "kind": "select",
        "options": [
          "1",
          "2",
          "3",
          "5",
          "7+"
        ],
        "required": true
      },
      {
        "id": "cost",
        "label": "Estimated cost (₹)",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Map dark store": {
    "advances": true,
    "fields": [
      {
        "id": "store",
        "label": "Dark store",
        "kind": "select",
        "options": [
          "DS-01 Indiranagar",
          "DS-02 Koramangala",
          "DS-03 HSR Layout",
          "DS-04 Whitefield",
          "DS-05 Jayanagar"
        ],
        "required": true
      },
      {
        "id": "distance",
        "label": "Distance from area centre",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Mark available": {
    "advances": true,
    "fields": [
      {
        "id": "check",
        "label": "Confirmed",
        "kind": "select",
        "options": [
          "Service complete",
          "Documents current",
          "Driver assigned"
        ],
        "required": true
      },
      {
        "id": "store",
        "label": "Return to store",
        "kind": "select",
        "options": [
          "DS-01 Indiranagar",
          "DS-02 Koramangala",
          "DS-03 HSR Layout",
          "DS-04 Whitefield",
          "DS-05 Jayanagar"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Mark delivered": {
    "advances": true,
    "fields": [
      {
        "id": "proof",
        "label": "Proof",
        "kind": "select",
        "options": [
          "OTP verified",
          "Photo at door",
          "Customer signature",
          "Left with security"
        ],
        "required": true
      },
      {
        "id": "code",
        "label": "OTP / reference",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Mark failed": {
    "advances": false,
    "fields": [
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Customer unavailable",
          "Address unreachable",
          "Customer refused",
          "Wrong address",
          "Safety concern"
        ],
        "required": true
      },
      {
        "id": "goods",
        "label": "Goods",
        "kind": "select",
        "options": [
          "Return to store",
          "Rider holds for reattempt",
          "Dispose — perishable"
        ],
        "required": true
      },
      {
        "id": "refund",
        "label": "Refund",
        "kind": "select",
        "options": [
          "Full refund",
          "No refund",
          "Decide later"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Mark off duty": {
    "advances": true,
    "fields": [
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Shift ended",
          "Weekly off",
          "Leave",
          "Unwell",
          "Vehicle unavailable"
        ],
        "required": true
      },
      {
        "id": "until2",
        "label": "Back on",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Mark on leave": {
    "advances": true,
    "fields": [
      {
        "id": "type",
        "label": "Leave type",
        "kind": "select",
        "options": [
          "Casual",
          "Sick",
          "Unpaid",
          "Emergency"
        ],
        "required": true
      },
      {
        "id": "from",
        "label": "From",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "to",
        "label": "To",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "cover",
        "label": "Stall cover",
        "kind": "select",
        "options": [
          "Reassign a colleague",
          "Close stall temporarily",
          "Leave unattended"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Mark priority": {
    "advances": true,
    "fields": [
      {
        "id": "level",
        "label": "Priority",
        "kind": "select",
        "options": [
          "Deliver first",
          "Deliver within window",
          "Standard"
        ],
        "required": true
      },
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Customer request",
          "Perishable items",
          "Compensation for earlier delay",
          "Corporate account"
        ],
        "required": true
      },
      {
        "id": "lock",
        "label": "Lock its position in the route",
        "kind": "select",
        "options": [
          "Yes",
          "No"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Match vehicle": {
    "advances": true,
    "fields": [
      {
        "id": "vehicle",
        "label": "Vehicle",
        "kind": "select",
        "options": [
          "KA-01 MH 4412 · Tata Ace · 750 kg",
          "KA-05 AB 8890 · Bajaj Auto · 350 kg",
          "KA-51 CD 1120 · Mahindra Jeeto · 500 kg",
          "KA-01 EF 7710 · Ashok Leyland Dost · 1,000 kg",
          "KA-09 GH 2240 · Bajaj Auto · 350 kg"
        ],
        "required": true
      },
      {
        "id": "weight",
        "label": "Load weight (kg)",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "check",
        "label": "Capacity check",
        "kind": "select",
        "options": [
          "Within capacity",
          "Needs a second trip"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Move stop": {
    "advances": true,
    "fields": [
      {
        "id": "stop3",
        "label": "Move stop",
        "kind": "select",
        "options": [
          "Stop 2",
          "Stop 3",
          "Stop 4",
          "Stop 5",
          "Stop 6"
        ],
        "required": true
      },
      {
        "id": "to",
        "label": "To position",
        "kind": "select",
        "options": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6"
        ],
        "required": true
      },
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Local knowledge",
          "Customer request",
          "Traffic",
          "Window pressure"
        ],
        "required": true
      },
      {
        "id": "recalc",
        "label": "After moving",
        "kind": "select",
        "options": [
          "Recalculate ETAs",
          "Leave ETAs"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Move to tomorrow": {
    "advances": true,
    "fields": [
      {
        "id": "slot",
        "label": "Tomorrow's slot",
        "kind": "select",
        "options": [
          "Morning run",
          "Afternoon run",
          "Evening run"
        ],
        "required": true
      },
      {
        "id": "goods",
        "label": "Goods overnight",
        "kind": "select",
        "options": [
          "Return to dark store",
          "Hold on vehicle — ambient only"
        ],
        "required": true
      },
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Customer unavailable",
          "Address not found",
          "Gate closed",
          "Customer rescheduled",
          "Ran out of run time"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Notify customer": {
    "advances": false,
    "fields": [
      {
        "id": "channel",
        "label": "Channel",
        "kind": "select",
        "options": [
          "SMS",
          "WhatsApp",
          "Call",
          "Email"
        ],
        "required": true
      },
      {
        "id": "message",
        "label": "Message",
        "kind": "select",
        "options": [
          "On the way with ETA",
          "Running late",
          "Arriving now",
          "Unloading",
          "Delivered — please sign"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Open customer": {
    "advances": false,
    "fields": [
      {
        "id": "view",
        "label": "Open",
        "kind": "select",
        "options": [
          "Customer profile",
          "Order history",
          "Acquisition source"
        ],
        "required": true
      }
    ]
  },
  "Open order": {
    "advances": false,
    "fields": [
      {
        "id": "view",
        "label": "Open",
        "kind": "select",
        "options": [
          "Order workspace",
          "Picking task",
          "Delivery tracking"
        ],
        "required": true
      }
    ]
  },
  "Optimise route": {
    "advances": true,
    "fields": [
      {
        "id": "basis",
        "label": "Optimise for",
        "kind": "select",
        "options": [
          "Shortest distance",
          "Fastest duration",
          "Meet every delivery window",
          "Balance distance and windows"
        ],
        "required": true
      },
      {
        "id": "locked",
        "label": "Respect locked stops",
        "kind": "select",
        "options": [
          "Yes",
          "No — re-sequence everything"
        ],
        "required": true
      },
      {
        "id": "start",
        "label": "Start from",
        "kind": "select",
        "options": [
          "Dark store",
          "Vehicle's current position"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Pause batch": {
    "advances": false,
    "fields": [
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Vehicle issue",
          "Operator break",
          "Weather",
          "Route blocked",
          "Awaiting decision"
        ],
        "required": true
      },
      {
        "id": "resume",
        "label": "Expected resume",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "customers",
        "label": "Notify remaining customers",
        "kind": "select",
        "options": [
          "Yes, with revised ETA",
          "No"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Plan stalls": {
    "advances": true,
    "fields": [
      {
        "id": "count",
        "label": "Stalls to plan",
        "kind": "select",
        "options": [
          "1",
          "2",
          "3",
          "4",
          "9"
        ],
        "required": true
      },
      {
        "id": "when",
        "label": "Target live date",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "owner",
        "label": "Field owner",
        "kind": "select",
        "options": [
          "Field ops · Nisha",
          "Field ops · Arjun",
          "Marketing · Pooja"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Preview incentive": {
    "advances": false,
    "fields": [
      {
        "id": "interactions",
        "label": "Interactions",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "registrations",
        "label": "Registrations",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "orders",
        "label": "First orders",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "value",
        "label": "Eligible order value (₹)",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "area",
        "label": "Area",
        "kind": "select",
        "options": [
          "Global rules only",
          "AREA-04 Whitefield",
          "AREA-03 HSR Layout"
        ],
        "required": true
      }
    ]
  },
  "Re-queue at end of run": {
    "advances": true,
    "fields": [
      {
        "id": "position",
        "label": "Insert as",
        "kind": "select",
        "options": [
          "Last stop",
          "After the next stop",
          "Before the final stop"
        ],
        "required": true
      },
      {
        "id": "eta",
        "label": "Revised ETA",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Re-route remaining": {
    "advances": true,
    "fields": [
      {
        "id": "basis3",
        "label": "Re-optimise for",
        "kind": "select",
        "options": [
          "Fastest recovery",
          "Windows most at risk first",
          "Shortest remaining distance"
        ],
        "required": true
      },
      {
        "id": "skip",
        "label": "Include skipped stops",
        "kind": "select",
        "options": [
          "Yes, at the end",
          "No"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Reassign rider": {
    "advances": false,
    "effect": "rider",
    "fields": [
      {
        "id": "rider",
        "label": "New rider",
        "kind": "select",
        "options": [
          "Vikram J.",
          "Imran A.",
          "Naveen R.",
          "Sameer Q.",
          "Deepak T."
        ],
        "required": true
      },
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Rider unavailable",
          "Vehicle issue",
          "Delay risk",
          "Zone change",
          "Rider declined"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Reassign stall": {
    "advances": true,
    "fields": [
      {
        "id": "stall",
        "label": "New stall",
        "kind": "select",
        "options": [
          "CS-014 Koramangala 8th",
          "CS-033 Whitefield Hope Farm",
          "CS-035 Whitefield Kadugodi"
        ],
        "required": true
      },
      {
        "id": "from",
        "label": "Effective from",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Performance",
          "Stall closed",
          "Employee request",
          "Area rebalance",
          "Cover for leave"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Reassign to rider": {
    "advances": true,
    "fields": [
      {
        "id": "rider",
        "label": "Rider",
        "kind": "select",
        "options": [
          "Vikram J.",
          "Imran A.",
          "Naveen R.",
          "Sameer Q.",
          "Deepak T."
        ],
        "required": true
      },
      {
        "id": "when2",
        "label": "Pick up from",
        "kind": "select",
        "options": [
          "Vehicle at next stop",
          "Back at the dark store"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Reattempt delivery": {
    "advances": true,
    "fields": [
      {
        "id": "when",
        "label": "Reattempt",
        "kind": "select",
        "options": [
          "Now",
          "In 30 minutes",
          "Later today",
          "Tomorrow"
        ],
        "required": true
      },
      {
        "id": "rider",
        "label": "Rider",
        "kind": "select",
        "options": [
          "Same rider",
          "Vikram J.",
          "Imran A.",
          "Naveen R.",
          "Sameer Q.",
          "Deepak T."
        ],
        "required": true
      },
      {
        "id": "contact",
        "label": "Contact customer first",
        "kind": "select",
        "options": [
          "Yes",
          "No"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Reattempt stop": {
    "advances": true,
    "fields": [
      {
        "id": "when",
        "label": "Reattempt",
        "kind": "select",
        "options": [
          "At the end of this run",
          "Next run from this store",
          "Tomorrow's first run"
        ],
        "required": true
      },
      {
        "id": "contact",
        "label": "Contact customer first",
        "kind": "select",
        "options": [
          "Yes — call now",
          "Yes — send SMS",
          "No"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Reattribute conversion": {
    "advances": false,
    "fields": [
      {
        "id": "to",
        "label": "Attribute to",
        "kind": "select",
        "options": [
          "Different stall",
          "Different employee",
          "Organic — no stall"
        ],
        "required": true
      },
      {
        "id": "stall",
        "label": "Stall",
        "kind": "select",
        "options": [
          "CS-001 Indiranagar 100ft",
          "CS-010 Koramangala 5th",
          "CS-019 HSR Sector 2",
          "CS-028 Whitefield ITPL"
        ],
        "required": true
      },
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Wrong stall recorded",
          "Employee changed mid-interaction",
          "Customer already registered",
          "Duplicate record"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Justification",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Reconcile allocation": {
    "advances": true,
    "fields": [
      {
        "id": "distributed",
        "label": "Distributed",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "returned",
        "label": "Returned unused",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "wastage",
        "label": "Wastage / spoilage",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Record distribution": {
    "advances": true,
    "fields": [
      {
        "id": "qty",
        "label": "Units distributed",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "date",
        "label": "Date",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "interactions",
        "label": "Customer interactions",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Refund delivery": {
    "advances": false,
    "fields": [
      {
        "id": "scope",
        "label": "Refund",
        "kind": "select",
        "options": [
          "Delivery fee only",
          "Full order",
          "Partial"
        ],
        "required": true
      },
      {
        "id": "amount",
        "label": "Amount (₹)",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "method",
        "label": "Refund to",
        "kind": "select",
        "options": [
          "Original payment method",
          "Selorg wallet"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Reason",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Refund order": {
    "advances": false,
    "fields": [
      {
        "id": "scope",
        "label": "Refund",
        "kind": "select",
        "options": [
          "Full order",
          "Delivery fee only",
          "Partial"
        ],
        "required": true
      },
      {
        "id": "amount",
        "label": "Amount (₹)",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "method",
        "label": "Refund to",
        "kind": "select",
        "options": [
          "Original payment method",
          "Selorg wallet"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Reason",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Release with salary": {
    "advances": true,
    "fields": [
      {
        "id": "month",
        "label": "Salary month",
        "kind": "select",
        "options": [
          "August 2026",
          "September 2026"
        ],
        "required": true
      },
      {
        "id": "date",
        "label": "Pay date",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "method",
        "label": "Method",
        "kind": "select",
        "options": [
          "Bank transfer",
          "UPI"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Remove from batch": {
    "advances": false,
    "fields": [
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Order cancelled",
          "Window no longer achievable",
          "Capacity exceeded",
          "Customer rescheduled",
          "Wrong area"
        ],
        "required": true
      },
      {
        "id": "route",
        "label": "Route",
        "kind": "select",
        "options": [
          "Re-optimise remaining stops",
          "Keep existing sequence"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Remove stop": {
    "advances": false,
    "fields": [
      {
        "id": "stop4",
        "label": "Stop",
        "kind": "select",
        "options": [
          "Stop 2",
          "Stop 3",
          "Stop 4",
          "Stop 5",
          "Stop 6"
        ],
        "required": true
      },
      {
        "id": "what",
        "label": "The order then",
        "kind": "select",
        "options": [
          "Returns to bulk queue",
          "Goes to a standard rider",
          "Held at store"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Reason",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Renew document": {
    "advances": true,
    "fields": [
      {
        "id": "doc",
        "label": "Document",
        "kind": "select",
        "options": [
          "Insurance",
          "Fitness certificate",
          "Permit",
          "Pollution certificate",
          "Road tax"
        ],
        "required": true
      },
      {
        "id": "until",
        "label": "New expiry",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "ref",
        "label": "Reference number",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Renew licence": {
    "advances": true,
    "fields": [
      {
        "id": "cls",
        "label": "Licence class",
        "kind": "select",
        "options": [
          "LMV",
          "LMV-TR",
          "HMV"
        ],
        "required": true
      },
      {
        "id": "until",
        "label": "New expiry",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "ref",
        "label": "Licence number",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Reorder samples": {
    "advances": true,
    "fields": [
      {
        "id": "qty",
        "label": "Quantity",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "priority",
        "label": "Priority",
        "kind": "select",
        "options": [
          "Urgent — stall idle",
          "Normal",
          "Next cycle"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Replace creative": {
    "advances": true,
    "fields": [
      {
        "id": "asset",
        "label": "New creative",
        "kind": "select",
        "options": [
          "banner-monsoon-hero.jpg",
          "banner-dairy-99.jpg",
          "onam-hero-v2.jpg",
          "Upload new"
        ],
        "required": true
      },
      {
        "id": "type",
        "label": "Material",
        "kind": "select",
        "options": [
          "Poster",
          "Standee",
          "Banner",
          "Digital creative"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Report stop issue": {
    "advances": false,
    "fields": [
      {
        "id": "issue",
        "label": "Issue",
        "kind": "select",
        "options": [
          "Wrong address",
          "Customer refused",
          "Damaged on arrival",
          "Wrong bag on vehicle",
          "Payment not collected",
          "Safety concern"
        ],
        "required": true
      },
      {
        "id": "bag",
        "label": "Bag",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "action",
        "label": "Action",
        "kind": "select",
        "options": [
          "Return bag to store",
          "Replace from next run",
          "Refund the customer",
          "Continue the run"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Details",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Resolve exception": {
    "advances": true,
    "fields": [
      {
        "id": "outcome",
        "label": "Outcome",
        "kind": "select",
        "options": [
          "Delivered on reattempt",
          "Returned to store",
          "Reassigned to rider",
          "Refunded",
          "Customer rescheduled",
          "No action needed"
        ],
        "required": true
      },
      {
        "id": "route4",
        "label": "Remaining route",
        "kind": "select",
        "options": [
          "Continue as planned",
          "Re-optimised",
          "Batch closed early"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Resolution note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Resume batch": {
    "advances": true,
    "fields": [
      {
        "id": "from",
        "label": "Resume at",
        "kind": "select",
        "options": [
          "Next stop in sequence",
          "Re-optimise remaining stops"
        ],
        "required": true
      },
      {
        "id": "eta2",
        "label": "Revised last-stop ETA",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Retire vehicle": {
    "advances": false,
    "fields": [
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "End of lease",
          "Beyond economical repair",
          "Sold",
          "Replaced",
          "Failed fitness"
        ],
        "required": true
      },
      {
        "id": "when",
        "label": "Effective",
        "kind": "select",
        "options": [
          "Immediately",
          "End of month"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Return to store": {
    "advances": true,
    "fields": [
      {
        "id": "goods2",
        "label": "Goods condition",
        "kind": "select",
        "options": [
          "Intact — restock",
          "Perishable — check cold chain",
          "Damaged — write off"
        ],
        "required": true
      },
      {
        "id": "refund",
        "label": "Customer",
        "kind": "select",
        "options": [
          "Full refund",
          "Reschedule delivery",
          "Awaiting customer contact"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Review performance": {
    "advances": true,
    "fields": [
      {
        "id": "period",
        "label": "Period",
        "kind": "select",
        "options": [
          "Last 30 days",
          "Last quarter",
          "Year to date"
        ],
        "required": true
      },
      {
        "id": "verdict",
        "label": "Verdict",
        "kind": "select",
        "options": [
          "Promote to preferred",
          "Maintain",
          "Place under review",
          "Reduce allocation"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Run dispatch checklist": {
    "advances": true,
    "fields": [
      {
        "id": "orders",
        "label": "All orders racked and ready",
        "kind": "select",
        "options": [
          "Yes",
          "No — 1 still packing"
        ],
        "required": true
      },
      {
        "id": "vehicle2",
        "label": "Vehicle available and within capacity",
        "kind": "select",
        "options": [
          "Yes",
          "No"
        ],
        "required": true
      },
      {
        "id": "operator2",
        "label": "Operator assigned and reported",
        "kind": "select",
        "options": [
          "Yes",
          "No"
        ],
        "required": true
      },
      {
        "id": "route3",
        "label": "Route optimised and applied",
        "kind": "select",
        "options": [
          "Yes",
          "No"
        ],
        "required": true
      },
      {
        "id": "exceptions",
        "label": "No blocking exceptions",
        "kind": "select",
        "options": [
          "Yes",
          "No"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Schedule campaign": {
    "advances": true,
    "fields": [
      {
        "id": "start",
        "label": "Starts",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "end",
        "label": "Ends",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "stalls",
        "label": "Stalls covered",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "spend",
        "label": "Budget (₹)",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Schedule rule": {
    "advances": true,
    "fields": [
      {
        "id": "start",
        "label": "Starts",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "end",
        "label": "Ends",
        "kind": "text",
        "options": [],
        "required": false
      },
      {
        "id": "scope",
        "label": "Scope",
        "kind": "select",
        "options": [
          "Global",
          "Bengaluru",
          "Single dark store"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Set area target": {
    "advances": true,
    "fields": [
      {
        "id": "metric",
        "label": "Target on",
        "kind": "select",
        "options": [
          "First orders per day",
          "Conversion rate",
          "Interactions per stall"
        ],
        "required": true
      },
      {
        "id": "value",
        "label": "Target value",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "period",
        "label": "Review",
        "kind": "select",
        "options": [
          "Weekly",
          "Monthly"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Set delivery mode": {
    "advances": true,
    "fields": [
      {
        "id": "mode",
        "label": "Mode",
        "kind": "select",
        "options": [
          "Single · cycle (1–2 orders)",
          "Single · bike (up to 3 orders)",
          "Bulk · e-auto (40–50 orders)"
        ],
        "required": true
      },
      {
        "id": "radius",
        "label": "Serves within",
        "kind": "select",
        "options": [
          "2 km",
          "4 km",
          "6 km",
          "Whole zone"
        ],
        "required": true
      },
      {
        "id": "from",
        "label": "Effective",
        "kind": "select",
        "options": [
          "Next shift",
          "Immediately"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Set fixed salary": {
    "advances": true,
    "fields": [
      {
        "id": "amount",
        "label": "Monthly fixed salary (₹)",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "from",
        "label": "Effective from",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "New hire",
          "Annual revision",
          "Promotion",
          "Correction",
          "Role change"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Skip stop": {
    "advances": false,
    "fields": [
      {
        "id": "stop5",
        "label": "Stop",
        "kind": "select",
        "options": [
          "Stop 2",
          "Stop 3",
          "Stop 5",
          "Stop 6"
        ],
        "required": true
      },
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Customer unavailable",
          "Address not found",
          "Delivery refused",
          "Gate closed",
          "Unsafe to stop"
        ],
        "required": true
      },
      {
        "id": "goods",
        "label": "The order",
        "kind": "select",
        "options": [
          "Return to store on this trip",
          "Reattempt at end of route",
          "Reassign to a rider",
          "Refund and return"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Split batch": {
    "advances": true,
    "fields": [
      {
        "id": "into",
        "label": "Split into",
        "kind": "select",
        "options": [
          "2 trips, same vehicle",
          "2 vehicles",
          "3 trips"
        ],
        "required": true
      },
      {
        "id": "basis2",
        "label": "Split by",
        "kind": "select",
        "options": [
          "Weight",
          "Geographic cluster",
          "Delivery window",
          "Priority"
        ],
        "required": true
      },
      {
        "id": "second",
        "label": "Second vehicle",
        "kind": "select",
        "options": [
          "Same vehicle, return trip",
          "KA-01 MH 4412 · Tata Ace",
          "KA-51 CD 1120 · Jeeto"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Split into trips": {
    "advances": true,
    "fields": [
      {
        "id": "trips",
        "label": "Number of trips",
        "kind": "select",
        "options": [
          "2",
          "3"
        ],
        "required": true
      },
      {
        "id": "basis",
        "label": "Split by",
        "kind": "select",
        "options": [
          "Weight",
          "Item category",
          "Delivery priority",
          "Chilled and ambient"
        ],
        "required": true
      },
      {
        "id": "second",
        "label": "Second trip vehicle",
        "kind": "select",
        "options": [
          "Same vehicle, return trip",
          "KA-01 MH 4412 · Tata Ace",
          "KA-51 CD 1120 · Mahindra Jeeto"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Submit for approval": {
    "advances": true,
    "fields": [
      {
        "id": "approver",
        "label": "Approver",
        "kind": "select",
        "options": [
          "Finance Admin",
          "Super Admin"
        ],
        "required": true
      },
      {
        "id": "effective",
        "label": "Requested effective date",
        "kind": "text",
        "options": [],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "Suspend employee": {
    "advances": false,
    "fields": [
      {
        "id": "reason",
        "label": "Reason",
        "kind": "select",
        "options": [
          "Conduct",
          "Falsified conversions",
          "Sample misuse",
          "Repeated absence",
          "Under investigation"
        ],
        "required": true
      },
      {
        "id": "length",
        "label": "Suspend for",
        "kind": "select",
        "options": [
          "Pending review",
          "7 days",
          "30 days",
          "Indefinite"
        ],
        "required": true
      },
      {
        "id": "pay",
        "label": "Pay during suspension",
        "kind": "select",
        "options": [
          "Salary only, no incentive",
          "Withhold both",
          "Full pay"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": true
      }
    ]
  },
  "Track live": {
    "advances": false,
    "fields": [
      {
        "id": "view",
        "label": "Show",
        "kind": "select",
        "options": [
          "Current position",
          "Route so far",
          "Full trip trail"
        ],
        "required": true
      }
    ]
  },
  "Unlock stop": {
    "advances": true,
    "fields": [
      {
        "id": "stop2",
        "label": "Stop",
        "kind": "select",
        "options": [
          "Stop 1",
          "Stop 2",
          "Stop 3"
        ],
        "required": true
      },
      {
        "id": "then",
        "label": "Then",
        "kind": "select",
        "options": [
          "Re-optimise remaining",
          "Leave sequence as is"
        ],
        "required": true
      },
      {
        "id": "note",
        "label": "Note",
        "kind": "textarea",
        "options": [],
        "required": false
      }
    ]
  },
  "View attribution": {
    "advances": false,
    "fields": [
      {
        "id": "depth",
        "label": "Show",
        "kind": "select",
        "options": [
          "Area, stall and employee",
          "Full journey to delivery",
          "Incentive impact"
        ],
        "required": true
      }
    ]
  },
  "View calculation": {
    "advances": false,
    "fields": [
      {
        "id": "depth",
        "label": "Show",
        "kind": "select",
        "options": [
          "Applied rules only",
          "Full calculation trace",
          "Rule versions used"
        ],
        "required": true
      }
    ]
  }
};
