import type { AdminUser } from "@/types/auth";

/** Adapted from the Admin Users screen in the approved design (dc.html ~6492). */
export const SEED_ADMIN_USERS: AdminUser[] = [
  {
    id: "U-01",
    name: "Arun K.",
    email: "arun@selorg.in",
    role: "Super Admin",
    scope: "All",
    twoFactorEnabled: true,
    status: "active",
    fullName: "Arun Kumar",
    phone: "+91 98450 10022",
    scopeLabel: "All warehouses and dark stores",
    employeeId: "SEL-EMP-0001",
    reportingTo: "Founder's office",
    joined: "14 Jan 2025",
  },
  {
    id: "U-02",
    name: "Kiran D.",
    email: "kiran@selorg.in",
    role: "Operations Admin",
    scope: "All",
    twoFactorEnabled: true,
    status: "active",
  },
  {
    id: "U-03",
    name: "Mahesh B.",
    email: "mahesh@selorg.in",
    role: "Warehouse Manager",
    scope: "WH-01",
    twoFactorEnabled: true,
    status: "active",
  },
  {
    id: "U-04",
    name: "Nisha R.",
    email: "nisha@selorg.in",
    role: "Dark Store Manager",
    scope: "DS-01",
    twoFactorEnabled: true,
    status: "active",
  },
  {
    id: "U-05",
    name: "Arjun P.",
    email: "arjun@selorg.in",
    role: "Rider Manager",
    scope: "All hubs",
    twoFactorEnabled: false,
    status: "active",
  },
  {
    id: "U-06",
    name: "Pooja V.",
    email: "pooja@selorg.in",
    role: "Customer Support",
    scope: "Global",
    twoFactorEnabled: true,
    status: "active",
  },
  {
    id: "U-07",
    name: "Latha S.",
    email: "latha@selorg.in",
    role: "Finance Admin",
    scope: "All",
    twoFactorEnabled: true,
    status: "active",
  },
  {
    id: "U-08",
    name: "Ravi T.",
    email: "ravi@selorg.in",
    role: "Catalog Manager",
    scope: "Global",
    twoFactorEnabled: false,
    status: "active",
  },
];
