import {
  LayoutDashboard,
  ShoppingCart,
  ClipboardList,
  PackageCheck,
  Boxes,
  Store,
  Warehouse,
  Users,
  Headset,
  Undo2,
  Wallet,
  Package,
  FolderTree,
  Tag,
  Newspaper,
  Home,
  Image,
  CalendarDays,
  Inbox,
  ArrowLeftRight,
  Building2,
  Bike,
  Map,
  UserCheck,
  UserCog,
  BadgeIndianRupee,
  ScrollText,
  Clock,
  CalendarClock,
  MessageCircleWarning,
  TriangleAlert,
  ScanBarcode,
  Bell,
  History,
  BarChart3,
  LineChart,
  Activity,
  UsersRound,
  UserSquare2,
  ClipboardCheck,
  KeyRound,
  Settings,
  Plug,
  UserCircle,
  Globe,
  ClipboardPlus,
  PackagePlus,
  FileSearch,
  CalendarCheck,
  ShieldCheck,
  Truck,
  BadgeCheck,
  FileCheck2,
  Layers,
  Route,
  Navigation,
  Car,
  Navigation2,
  LayoutGrid,
  ListOrdered,
  GanttChart,
  MapPin,
  Radar,
  HardHat,
  AlertOctagon,
  QrCode,
  FileSpreadsheet,
  UserPlus,
  PlusSquare,
  ShoppingBag,
  PackageSearch,
  ListChecks,
  MapPinned,
  Tent,
  IdCard,
  Filter,
  ReceiptText,
  Megaphone,
  FlaskConical,
  Award,
  Banknote,
  ChartNetwork,
  UserRoundSearch,
  ContactRound,
  IndianRupee,
  Waypoints,
  Star,
  TabletSmartphone,
} from "lucide-react";
import type { ComponentType } from "react";
import type { ModuleId } from "@/constants/nav";

type IconComponent = ComponentType<{ size?: number; strokeWidth?: number }>;

export const NAV_ICONS: Record<ModuleId, IconComponent> = {
  dashboard: LayoutDashboard,
  orders: ShoppingCart,
  "order-detail": ShoppingCart,
  picking: ClipboardList,
  bags: PackageCheck,
  racks: Boxes,
  stores: Store,
  "store-inv": Warehouse,
  "scan-history": History,
  customers: Users,
  support: Headset,
  returns: Undo2,
  payments: Wallet,
  catalog: Package,
  categories: FolderTree,
  promotions: Tag,
  cms: Newspaper,
  "cms-home": Home,
  "cms-media": Image,
  "cms-cal": CalendarDays,
  mastersheet: FileSpreadsheet,
  wh: Warehouse,
  "wh-inv": Boxes,
  inbound: Inbox,
  "inbound-asn": CalendarCheck,
  putaway: PackageCheck,
  transfers: ArrowLeftRight,
  "wh-approvals": ShieldCheck,
  "wh-transfer": Truck,
  "wh-transfer-approve": BadgeCheck,
  "wh-audit": FileCheck2,
  "wh-users": UserPlus,
  "wh-create": PlusSquare,
  "wh-products": PackageSearch,
  vendors: Building2,
  "ds-overview": Globe,
  "ds-users": UserPlus,
  "ds-products": ShoppingBag,
  "ds-request": ClipboardPlus,
  "ds-receive": PackagePlus,
  "ds-audit": FileSearch,
  "stall-overview": ChartNetwork,
  "stall-areas": MapPinned,
  stalls: Tent,
  "stall-staff": IdCard,
  "stall-conv": Filter,
  "stall-orders": ReceiptText,
  "stall-ads": Megaphone,
  "stall-samples": FlaskConical,
  "stall-incentives": Award,
  "stall-earnings": Banknote,
  "bd-stops": ListChecks,
  "bulk-orders": Layers,
  "bulk-dispatch": Route,
  "bulk-track": Navigation,
  vehicles: Car,
  riders: Bike,
  deliveries: Navigation2,
  "bd-overview": LayoutGrid,
  "bd-queue": ListOrdered,
  "bd-batches": GanttChart,
  "bd-route": MapPin,
  "bd-track": Radar,
  "bd-ops": HardHat,
  "bd-exceptions": AlertOctagon,
  zones: Map,
  "rider-approvals": UserCheck,
  "picker-approvals": UserCheck,
  "rider-dir": UserCog,
  "picker-dir": UserCog,
  "rider-details": UserRoundSearch,
  "picker-details": ContactRound,
  "rider-earn": BadgeIndianRupee,
  "picker-earn": BadgeIndianRupee,
  "earn-rules": ScrollText,
  payouts: Wallet,
  shifts: Clock,
  roster: CalendarClock,
  "rider-support": MessageCircleWarning,
  "picker-support": MessageCircleWarning,
  exceptions: TriangleAlert,
  "cod-collection": IndianRupee,
  "order-progress": Waypoints,
  "customer-reviews": Star,
  "hsd-devices": TabletSmartphone,
  scanner: ScanBarcode,
  barcodes: QrCode,
  notifications: Bell,
  audit: History,
  "rpt-overall": BarChart3,
  "rpt-sales": LineChart,
  "rpt-ops": Activity,
  "rpt-people": UsersRound,
  "rpt-customer": UserSquare2,
  reports: ClipboardCheck,
  users: Users,
  roles: KeyRound,
  settings: Settings,
  integrations: Plug,
  account: UserCircle,
  "api-catalog": Globe,
};
